dist: trusty
sudo: true

language: node_js
node_js:
  - 8

git:
  quiet: true

branches:
  only:
    - master
    - development
    - staging
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

addons:
  apt:
    sources:
      - google-chrome
      - mariadb-10.0
    packages:
      - google-chrome-stable
      - mariadb-server
      - mariadb-client
      - libmariadbclient-dev

cache:
  directories:
    - ./node_modules

before_install:
  - sudo apt-get update

install:
  - npm install
  - npm install coveralls

before_script:
  - cp ./config/db.cred.sample.ts ./config/db.cred.ts
  - cp ./config/database.sample.json ./config/database.json
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root
  - sudo service mysql restart
  - mysql -e 'CREATE DATABASE IF NOT EXISTS db;'

jobs:
  include:
    - stage: lint
      script:
        - npm run lint
    - stage: dev
      script:
        - npm run pugpostinstall
        - npm run build:ssr
        - npm run db:up:travis:all
        - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI --code-coverage
        - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
    - stage: stage
      script:
        - npm run pugpostinstall
        - npm run build:ssr:production
        - npm run db:up:travis:all
        - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI --code-coverage
        - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
    - stage: production
      script:
        - npm run pugpostinstall
        - npm run build:ssr:production
        - npm run db:up:travis:all
        - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI --code-coverage
        - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

stages:
  - lint
  - name: dev
    if: branch = development
  - name: stage
    if: branch = staging
  - name: production
    if: branch = master

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
